run:
    tests: false

issues:
    exclude-use-default: false

linters:
    disable-all: true
    enable:
        - govet
        - errcheck
        - staticcheck
        - unused
        - gosimple
        - bodyclose
        - noctx
        - golint
        - gosec
        - unconvert
        - goconst
        - gocyclo
        - gofmt
        - goimports
        - goheader
        - misspell
        - lll
        - prealloc

linters-settings:
    govet:
        check-shadowing: true
        settings:
            printf:
                funcs:
                    - (github.com/sirupsen/logrus.Logger).Infof
                    - (github.com/sirupsen/logrus.Logger).Warnf
                    - (github.com/sirupsen/logrus.Logger).Errorf
                    - (github.com/sirupsen/logrus.Logger).Fatalf

    errcheck:
        check-type-assertions: true
        check-blank: true

    goconst:
        min-len: 2
        min-occurrences: 4

    gofmt:
        simplify: true

    goimports:
        local-prefixes: github.com/sdslabs/pinger

    misspell:
        locale: US
        ignore-words: []

    lll:
        line-length: 120
        tab-width: 4

    gocyclo:
        min-complexity: 20

    goheader:
        values:
            const:
                COMPANY: SDSLabs
            regexp:
                YEAR: 202[0-9]
        template: "Copyright (c) {{ YEAR }} {{ COMPANY }}\n\
               Use of this source code is governed by an MIT license\n\
               details of which can be found in the LICENSE file."
